version: "3"
services:
  nginx:
    container_name: nginx
    # ======================================
    # read_only: true
    # ======================================
    # build:
    #     context: ./environment/nginx
    #     dockerfile: Dockerfile
    #
    build  : ./environment/nginx
    # ======================================
    restart: always
    # ======================================
    volumes: ["./workspace:/xrosy/src:ro"]
    # ======================================
    ports  : ["80:80", "443:443"]
    # ======================================
    links  : ["node10"]




  # ****************************************************************************
  node10:
    container_name: node10
    # ======================================
    image: node:10-alpine
    # ======================================
    # 从文件中获取环境变量，可以为单独的文件路径或列表。
    env_file: .env
    # ======================================
    # 以只读模式挂载容器的 root 文件系统
    read_only: true
    expose:
      - "3000"
    volumes:
      - ./workspace/net.zuojiao.operation:/xrosy/net.zuojiao.operation
    working_dir: /xrosy/net.zuojiao.operation
    command: "node server.js"
    # ======================================
    # 设置环境变量。你可以使用数组或字典两种格式。
    # environment:
    #   RACK_ENV: development
    #   SESSION_SECRET:
    #
    # environment:
    #   - RACK_ENV=development
    #   - SESSION_SECRET

    # ======================================
    # 通过命令检查容器是否健康运行
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3

    # ======================================
    # environment:
    #     KEY_NAME: VALUE

    # ======================================
    # 存储敏感数据
    # secrets:
    #   - db_root_password
    #   - my_other_secret

