version: '3'

services:
    nginx:
        build: ./docker/nginx
        restart: always
        environment:
            - development
        volumes:
            - ./docker/nginx/conf/vps:/etc/nginx/conf.d:ro
            - ./src/_www:/xrosy/src/_www:ro
        expose:
            - "80"
            - "8080"
        ports:
            - "80:80"
            - "443:443"

    # bioAdmin:
    #     image: node:alpine
    #     depends_on:
    #         - nginx