
FROM node:alpine

LABEL maintainer="XRosy-Node10 Docker Maintainers <jason@chenzhenyuan.com>"

EXPOSE 3000

STOPSIGNAL SIGTERM

# VOLUME [ "/xrosy/net.zuojiao.operation" ]

WORKDIR /xrosy/net.zuojiao.operation

CMD ["node", "server.js"]